<?php
@define('_workper', 'Vietnam Work Permit');
@define('_temporary', 'Temporary Resident');
@define('_giolamviec', 'Work time');
@define('_whatwedo', 'What We Do?');
@define('_deswhat', 'We advise and provide visa services for foreigners in Vietnam, foreigners residing in Vietnam.');
@define('_xemalldv', 'View all services');
@define('_tongquan', 'Project overview');
@define('_ykienkhachhang', 'Testimonials');

@define('_motadownload', 'Download the latest documentation on our');
@define('_xemthem', 'See more');
@define('_lichsu', 'History');
@define('_huongdanbaoduong', 'Tile Care');
@define('_chinhanh', 'Showroom');
@define('_ketnoi', 'Connect with us');
@define('_tiengviet', 'Vietnamese');
@define('_tienganh', 'English');
//------------ Menu -----------------
@define('_trangchu', ' Home');
@define('_gioithieu', ' Introduction');
@define('_tintuc', 'News');
@define('_sanpham', 'Product');
@define('_daily', 'Agent');
@define('_tuyendung', 'recruitment');
@define('_lienhe', 'Contact');

@define('_khachhang', 'Customers');
@define('_thietbi', 'Sanitary Wares');
@define('_dichvu', 'Services');
@define('_tintucsukien', 'News - Events');
@define('_xuatxu', 'Manufacturer');
@define('_menu', 'Menu');
@define('_hinhanh', 'Images');
@define('_video', 'Video clip');
@define('_sukien', 'Events');
@define('_khuyenmai', 'Promotions');
//---------------- / /
@define('_chitiet', 'Details');
@define('_dangluc', 'Last time');
@define('_daxem', 'Watched');
@define('_chitietbaiviet', 'details article');
@define('_cacbaivietkhac', 'Articles');
@define('_chitietsanpham', 'Product details');
@define('_gia', 'Price');
@define('_maso', 'Code');
@define('_luotxem', 'view');
@define('_sanphamcungloai', 'Orther prodcuts');
@define('_danhmucsanpham', 'Product Category');
@define('_hinhanhsanpham', 'Product Images');
@define('_thongketruycap', 'Counter');
@define('_homnay', 'To day');
@define('_trongthang', 'Month');
@define('_tongtruycap', 'Total');
@define('_dangonline', 'Online');
@define('_daonline', 'Have Online');
@define('_hotrotructuyen', 'Support online');
@define('_hotrokinhdoanhvatuvan', 'Business support and advice');
@define('_thongtinlienhe', 'Contact Information');
@define('_danhchoquangcao', 'For advertising');
@define('_doitac', 'Partner');
@define('_xemtatca', 'View all');
@define('_lienketwebsite', 'Links');
@define('_bando', 'map');
@define('_nhaptensp', 'Enter keywords to search');
@define('_timkiem', 'Search');
@define('_cacbaikhac', 'Orther News');
@define('_sanphamtieubieu', 'Typical products');
//----------------------------------
define('_gui', 'Submit');
define('_nhaplai', 'Reset');
define('_diachi', 'Address');
define('_sodienthoai', 'Phone');
define('_hovaten', 'name');
define('_chude', 'Subject');
define('_noidung', 'Content');
define('_ghichu', 'You can contact us from this website by filling the contact information into the form below. We will contact you in the shortest time. Please thank. ');

//-----------------------------------//
@define('_readmore', 'Read more');
@define('_stay', 'Stay in touch');
@define('_enteremail', 'Enter email');
@define('_xemtiep', 'Read more >>');

@define('_tieptuc', 'Continue');
@define('_thongtinkhachhang', 'Customer Information');
@define('_chuacodonhang', 'You are currently no orders');
@define('_lichsumuahang', 'Buying history');
@define('_conhang', 'In stock');
@define('_tinhtrang', 'Condition');
@define('_matkhaumoi', 'New password');
@define('_thongtintaikhoan', 'Account Information');
@define('_doimatkhau', 'Change password');
@define('_doithongtin', 'Account Information');
@define('_thoat', 'Logout');
@define('_laylaimatkhau', 'Retrieve password');
@define('_clearcart', 'Remove all products from the cart !');
@define('_delcart', 'Skip this product from the cart !');
@define('_hinhanh', 'Images');
@define('_thanhtoan', 'Payments');
@define('_capnhat', 'Update');
@define('_xoatatca', 'Clear all');
@define('_muatiep', 'Buy more');
@define('_tonggiaban', 'Total price');
@define('_tonggia', 'Total price');
@define('_soluong', 'Quantity');
@define('_ten', 'Name');
@define('_stt', 'No.');
@define('_emaildaduocsudung', 'The email you have entered user');
@define('_taikhoanitnhat4kytu', 'Account must be 4 or more characters');
@define('_taikhoandasudung', 'The account you already have a user enter');
@define('_dedoimatkhau', 'to change the password');
@define('_dagoipassvaomail', 'We have sent a new password to your email ! You need to mail');
@define('_doipassthanhcong', 'Change password succeed !');
@define('_capnhatthanhcong', 'Update successful !');
@define('_dangnhapthanhcong', 'Login successful !');
@define('_thuchienkichhoattaikhoan', 'to perform the activation');
@define('_dangkythanhcong', 'Sign up for success ! You need to mail');
@define('_dangxuatthanhcong', 'Logout successful');
@define('_nhanvaolinkdehoantat', 'Please click this link for complete');
@define('_bandayeucaulaylaimatkhautai', 'You have requested to retrieve passwords in');
@define('_yeucaulaylaimatkhautai', 'Require password retrieval at');
@define('_emailchuadangky', 'The email you entered is not registered');
@define('_loiemail', 'Email incorrect');
@define('_saimatkhaucu', 'The old password is not correct');
@define('_chuanhappassmoi', 'You did not enter the new password');
@define('_chuanhappasscu', 'You did not enter the old password');
@define('_dehoanthanh', 'to complete your registration please click on the link below to activate your account');
@define('_dangkytaitai', 'You have to register an account at the');
@define('_xinchao', 'Hello');
@define('_saimabaove', 'Wrong security code');
@define('_chuanhapdiachi', 'You have not entered address');
@define('_chuanhapsodienthoai', 'You did not enter a phone number');
@define('_golaimatkhausai', 'Passwords are not the same type 2 times');
@define('_matkhauitnhat6kytu', 'Password At least 6 characters');
@define('_chuanhaplaimatkhau', 'You did not enter a password');
@define('_chuanhapmatkhau_itnhat6kytu', 'You did not enter a password ( > = 6 characters )');
@define('_error_tendangnhap', 'Username least 6 characters');
@define('_tendangnhapkhongtontai', 'Username does not exist');
@define('_taikhoanchuakichhoat', 'Your account has not been activated');
@define('_quenmatkhau', 'Forgot password');
@define('_saitendangnhap', 'Username or password incorrect');
@define('_chuadienmabaove', 'You do not enter the security code .');
@define('_error_email', 'Please enter a valid email address');
@define('_chuadienmatkhau', 'You did not enter a password .');
@define('_chuadientendangnhap', 'You have no username .');
@define('_masp', 'Mã sản phẩm');
@define('_thongtinchitiet', 'Details');
@define('_sanphamnoibat', 'Hot Products');
@define('_lienketweb', 'Weblinks');
@define('_thoitrangxaominh', 'Xảo Minh Fashion ');
@define('_sanphammoi', 'New product');
@define('_dathang', 'Order');
@define('_chinhsach', 'Policy');
@define('_muangay', 'Buy now');
@define('_muathem', 'Buy more products');
@define('_tienhanh', 'Proceed to order');
@define('_nocart', 'No items in cart');
@define('_thongbao', 'Notice !');
@define('_bancoxoa', 'Are you sure you want to remove this product !');
@define('_dongy', 'Agree ');
@define('_khongdongy', 'Disagree');
@define('_daxoathanhcong', 'You removed the products succeed. ');
@define('_dahuyxoa', 'Cancelled deleting products. ');
@define('_giohang', 'Cart ');
@define('_dongia', 'Unit price ');
@define('_thanhtien', 'Amount ');
@define('_tongtien', 'Total ');
@define('_thongtindonhang', 'Information line ');
@define('_thongtinthanhtoan', 'Billing Information ');
@define('_diachinhanhang', 'Shipping Address ');
@define('_ghichudonhang', 'Note the line ');
@define('_chonhinhthucthanhtoan', 'Choose form of payment ');
@define('_thanhtoankhinhanhang', 'Payment on delivery ');
@define('_thanhtoanbaokim', 'Payment through security metal ');
@define('_thanhtoannganluong', 'Payment via cash amount ');
@define('_thanhtoan123', '123 payment through pay ');
@define('_chonnganhang', 'Choose payment bank');
@define('_banco', 'You have');
?>